disabled_rules:
  - nesting
  # using only a fallthrough is part of apple's recommended pattern for handling @unknown default
  -  no_fallthrough_only

opt_in_rules:
  - anyobject_protocol
  # - array_init #(the array_init swiftlint rule doesn't play well with some libs)
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  # - discouraged_optional_collection # sometimes needed (AppDelegate)
  # Rationale: Provides consistency in coding style
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - explicit_top_level_acl # there's also explicit_acl which is even stricter
  # - no_extension_access_modifier
  - extension_access_modifier
  - fatal_error_message
  - file_length
  - file_name
  - file_name_no_space
  - file_types_order
  - first_where
  - for_where
  - force_unwrapping
  - force_try
  - function_default_parameter_at_end
  - identical_operands
 #  - implicit_return: # rule currently isn't respecting configuration, not needed in most cases anyway
 #     included:
 #       - closure
 #       - getter
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_objc_type
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  # Rationale: Public API's should be documented
  - missing_docs
  - modifier_order
  - multiline_arguments
  # - multiline_function_chains
  # Rationale: Provides consistency in coding style
  - multiline_literal_brackets
  - multiple_closures_with_trailing_closure
  # Rationale: Provides consistency in coding style
  - multiline_parameters
  - nimble_operator
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  # - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test  
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - type_contents_order
  # Rationale: Prevents coder error
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_import
  - unused_declaration
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition

excluded:
  - Pods
  - Sources/AppcuesKit/Version.swift

# listing the SL default values 
cyclomatic_complexity:
  warning: 15
  error: 20

# couldn't get this to work :-/
#explicit_type_interface:
#  excluded: local, static, instance
#  allow_redundancy: true

file_length:
  warning: 750   #default == 400
  error: 2000    #default == 1000

line_length:
  warning: 140
  ignores_urls: true

# doesn't seem accurate but is on by default
type_body_length:
  - 250  # warning - default is 200
  - 350 # error


identifier_name:
  max_length:
    warning: 80
    error: 80
  min_length:
    error: 3
  excluded:
    - key
    - i
    - id
    - ok
    - on
    - url
    - up
    - ad

vertical_whitespace:
  max_empty_lines: 1

missing_docs:
  excludes_extensions: true
  excludes_inherited_types: true
