name: Appcues
attributes:
  ORGANIZATIONNAME: Appcues
options:
  defaultConfig: Release
  deploymentTarget:
    iOS: 11.0
  groupSortPosition: top
configs:
  Debug: debug
  Release: release
settings:
  base:
    CLANG_CXX_LANGUAGE_STANDARD: gnu++17
schemes:
  Appcues:
    analyze:
      config: Debug
    archive:
      config: Release
    build:
      targets:
        AppcuesKit:
        - analyzing
        - testing
        - running
        - profiling
        - archiving
    profile:
      config: Release
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
      - AppcuesKitTests
targets:
  AppcuesKit:
    type: framework
    platform: iOS
    settings:
      base:
        MARKETING_VERSION: 0.1.0
        GENERATE_INFOPLIST_FILE: 'YES'
        PRODUCT_BUNDLE_IDENTIFIER: com.appcues.sdk
    sources:
    - path: Sources/AppcuesKit
    - path: Sources/AppcuesKit/AppcuesKit.docc
      buildPhase: sources
    preBuildScripts:
    - name: SwiftGen
      script: xcrun --sdk macosx mint run swiftgen config run
    postbuildScripts:
    - name: SwiftLint
      script: 'xcrun --sdk macosx mint run swiftlint --path ./Sources'
  AppcuesKitTests:
    dependencies:
    - target: AppcuesKit
    platform: iOS
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: 13.0
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: '1'
        GENERATE_INFOPLIST_FILE: 'YES'
        PRODUCT_BUNDLE_IDENTIFIER: com.appcues.AppcuesKitTests
    sources:
    - path: Tests/AppcuesKitTests
    type: bundle.unit-test
