version: 2.1

# -------------------------
#       PARAMETERS
# -------------------------
parameters:
  deploy-beta:
    type: boolean
    default: false

# -------------------------
#          ORBS
# -------------------------
orbs:
  slack: circleci/slack@4.4.4

# -------------------------
#        EXECUTORS
# -------------------------
executors:
  xcode_13:
    macos:
      xcode: 13.0.0
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -o pipefail
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1

# -------------------------
#        REFERENCES
# -------------------------
references:
  is_main: &is_main
    matches:
      pattern: '^main$'
      value: << pipeline.git.branch >>

# -------------------------
#          COMMANDS
# -------------------------
commands:
  install_with_cache:
    description: 'Checkout from git and install gem and mint dependencies'
    steps:
      - checkout
      - restore_cache:
          name: Restore gem cache
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install gem dependencies
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          name: Save gem cache
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Install mint (Swift dependency manager)
          command: brew install mint
      - restore_cache:
          name: Restore swift build package cache
          key: 3-mint-{{ checksum "Mintfile" }}
      - run:
          name: Install swift build packages
          command: mint bootstrap
      - save_cache:
          name: Save swift build package cache
          key: 3-mint-{{ checksum "Mintfile" }}
          paths:
            - /usr/local/lib/mint

# -------------------------
#          JOBS
# -------------------------
jobs:
  validate_code:
    executor: xcode_13
    steps:
      - install_with_cache
      - run:
          name: Run fastlane tests
          command: bundle exec fastlane validate_code
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: team-mobile-bots

  deploy_example:
    executor: xcode_13
    steps:
      - install_with_cache
      - run:
          name: Run beta build
          command: bundle exec fastlane beta_example
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: team-mobile-bots

# -------------------------
#        WORKFLOWS
# -------------------------
workflows:
  version: 2
  pr_validation:
    unless: *is_main
    jobs:
      - validate_code:
          context:
            - Appcues

  build_and_deploy:
    when:
      and:
        - *is_main
        - << pipeline.parameters.deploy-beta >>
    jobs:
      - deploy_example:
          context:
            - Appcues
