version: 2.1
orbs:
  macos: circleci/macos@2
jobs:
  run_tests:
    macos:
      xcode: 13.0.0
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -o pipefail
    environment:
      MINT_PATH: ".mint"
      MINT_LINK_PATH: "$MINT_PATH/bin"
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - macos/preboot-simulator:
          version: "15.0"
          platform: "iOS"
          device: "iPhone 13"
      - checkout
      - restore_cache:
          name: Restore gem cache
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install gem dependencies
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          name: Save gem cache
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Install mint (Swift dependency manager)
          command: brew install mint
      - restore_cache:
          name: Restore swift build package cache
          key: 1-mint-{{ checksum "Mintfile" }}
      - run:
          name: Install swift build packages
          command: mint bootstrap
      - save_cache:
          name: Save swift build package cache
          key: 1-mint-{{ checksum "Mintfile" }}
          paths:
            - .mint
      - run:
          name: Run fastlane tests
          command: bundle exec fastlane validate_code
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
workflows:
  version: 2
  pr_validation:
    jobs:
      - run_tests:
          filters:
            branches:
              ignore:
                - main
