version: 2.1
jobs:
  run_tests:
    macos:
      xcode: 13.0.0
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -o pipefail
    environment:
      MINT_PATH: ".mint"
      MINT_LINK_PATH: "$MINT_PATH/bin"
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: brew install mint
      - restore_cache:
          key: 1-mint-{{ checksum "Mintfile" }}
      - run: mint bootstrap
      - save_cache:
          key: 1-mint-{{ checksum "Mintfile" }}
          paths:
            - .mint
      - run: bundle exec fastlane sdktests
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
workflows:
  version: 2
  pr_validation:
    jobs:
      - run_tests:
          filters:
            branches:
              ignore:
                - main
