version: 2.1
jobs:
  test:
    macos:
      xcode: 13.0.0
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: brew install mint
      - run: mint run xcodegen
      - run: mint run swiftlint
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec fastlane test
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
workflows:
  version: 2
  pr_validation:
    jobs:
      - test
        filters:
            branches:
              ignore:
                - main
