default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Validate the code in the SDK repo works properly"
  lane :validate_code do
    sdk_tests
    compile_cocoapods_example
    compile_spm_example
  end

  desc "Run SDK unit tests"
  lane :sdk_tests do
    Dir.chdir("..") do
      sh("mint run xcodegen")
    end
    run_tests(scheme: "Appcues",
              devices: ["iPhone 13"])
  end

  desc "Sanity check to make sure the cocoapods example app compiles"
  lane :compile_cocoapods_example do
    cocoapods(podfile: "Examples/DeveloperCocoapodsExample/Podfile")
    sh("sh", "./replace-placeholders.sh", "DeveloperCocoapodsExample/CocoapodsExample", "00000", "abc")
    build_app(
      workspace: "Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.xcworkspace",
      skip_archive: true,
      skip_codesigning: true)
  end

  desc "Sanity check to make sure the spm example app compiles"
  lane :compile_spm_example do
    sh("sh", "./replace-placeholders.sh", "DeveloperSPMExample/SPMExample", "00000", "abc")
    build_app(
      project: "Examples/DeveloperSPMExample/AppcuesSPMExample.xcodeproj",
      skip_archive: true,
      skip_codesigning: true)
  end

  desc "Setup code signing"
  lane :prep_match do
    app_store_connect_api_key

    sync_code_signing(
      storage_mode: "s3",
      s3_region: ENV["AWS_REGION"],
      s3_bucket: ENV["AWS_S3_BUCKET"],
      s3_access_key: ENV["AWS_ACCESS_KEY_ID"],
      s3_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
      type: "appstore",
      app_identifier: "com.appcues.sdk-example-cocoapods",
      team_id: "KHSQ25769M",
      verbose: true)
  end

  desc "Push example app to Testflight beta"
  lane :beta_example do | options |
    app_store_connect_api_key

    current_build = latest_testflight_build_number(
      api_key: ENV["APP_STORE_CONNECT_API_KEY"],
      app_identifier: "com.appcues.sdk-example-cocoapods")

    increment_build_number(
      build_number: current_build + 1,
      xcodeproj: "Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.xcodeproj")

    cocoapods(podfile: "Examples/DeveloperCocoapodsExample/Podfile")
    sh("sh", "./replace-placeholders.sh", "DeveloperCocoapodsExample/CocoapodsExample", ENV["EX_APPCUES_ACCOUNT_ID"], ENV["EX_APPCUES_APPLICATION_ID"])

    sync_code_signing(
      storage_mode: "s3",
      s3_region: ENV["AWS_REGION"],
      s3_bucket: ENV["AWS_S3_BUCKET"],
      s3_access_key: ENV["AWS_ACCESS_KEY_ID"],
      s3_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
      type: "appstore",
      app_identifier: "com.appcues.sdk-example-cocoapods",
      team_id: "KHSQ25769M",
      readonly: true,
      verbose: true)

    update_code_signing_settings(
      use_automatic_signing: false,
      code_sign_identity: "iPhone Distribution",
      team_id: ENV["sigh_com.appcues.sdk-example-cocoapods_appstore_team-id"],
      profile_uuid: ENV["sigh_com.appcues.sdk-example-cocoapods_appstore"],
      path: "Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.xcodeproj")

    build_app(
      export_method: "app-store",
      workspace: "Examples/DeveloperCocoapodsExample/AppcuesCocoapodsExample.xcworkspace")
        
    git_log = changelog_from_git_commits(
      commits_count: 5,
      pretty: "- [%as] %s"
    )
    changelog = "Latest commits on #{ENV["CIRCLE_BRANCH"]}:\n" + git_log + "\n\nCircleCI Build: #{ENV["CIRCLE_BUILD_NUM"]}"
    
    upload_to_testflight(
      api_key: ENV["APP_STORE_CONNECT_API_KEY"],
      changelog: changelog,
      skip_submission: true)
  end
end
