name: AppcuesCocoapodsExample
options:
  defaultConfig: Release
  bundleIdPrefix: com.appcues
  deploymentTarget:
    iOS: 13.0
  postGenCommand: pod install
  groupSortPosition: top
schemes:
  AppcuesCocoapodsExample:
    build:
      targets:
        AppcuesCocoapodsExample:
        - running
        - testing
        - profiling
        - analyzing
        - archiving
targets:
  AppcuesCocoapodsExample:
    type: application
    platform: iOS
    sources:
    - path: CocoapodsExample
    dependencies:
      - target: NotificationServiceExtension
    entitlements:
      path: AppcuesCocoapodsExample.entitlements
      properties:
        aps-environment: development
        com.apple.developer.associated-domains:
          - applinks:appcues-mobile-links.netlify.app
    postbuildScripts:
    - name: SwiftLint
      script: 'if which mint >/dev/null; then

            xcrun --sdk macosx mint run swiftlint@0.50.3

        else

            echo "warning: Mint not installed, install from https://github.com/yonaskolb/Mint"

        fi
        '
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.appcues.sdk-example-cocoapods
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    attributes:
      # necessary for fastlane/xcode16 issue: fastlane rejects an empty TargetAttributes
      # in update_code_signing_settings. If you open the project with Xcode 16 then TargetAttributes
      # gets removed if it's empty.
      # https://github.com/fastlane/fastlane/pull/23872
      some_flag: false
  NotificationServiceExtension:
    type: app-extension
    platform: iOS
    sources:
    - path: NotificationServiceExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.appcues.sdk-example-cocoapods.notification-service
settings:
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: 'YES'
