name: AppcuesCocoapodsExample
options:
  defaultConfig: Release
  bundleIdPrefix: com.appcues
  deploymentTarget:
    iOS: 13.0
  postGenCommand: pod install
  groupSortPosition: top
targets:
  AppcuesCocoapodsExample:
    type: application
    platform: iOS
    sources:
    - path: CocoapodsExample
    entitlements:
      path: AppcuesCocoapodsExample.entitlements
      properties:
        com.apple.developer.associated-domains:
          - applinks:appcues-mobile-links.netlify.app
    postbuildScripts:
    - name: SwiftLint
      script: 'if which mint >/dev/null; then

            xcrun --sdk macosx mint run swiftlint@0.44.0

        else

            echo "warning: Mint not installed, install from https://github.com/yonaskolb/Mint"

        fi
        '
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.appcues.sdk-example-cocoapods
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
